default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: <%= Rails.application.credentials.postgres[:host] %>

development:
  <<: *default
  database: api_passforge_development

test:
  <<: *default
  database: api_passforge_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>