default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: api_passforge_development
  username: <%= Rails.application.credentials.dig(:postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  host: <%= Rails.application.credentials.dig(:postgres, :host) %>

test:
  <<: *default
  database: api_passforge_test
  username: <%= Rails.application.credentials.dig(:postgres, :username) %>
  password: <%= Rails.application.credentials.dig(:postgres, :password) %>
  host: <%= Rails.application.credentials.dig(:postgres, :host) %>

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>