default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if Rails.application.credentials.postgres.present? %>
  username: <%= Rails.application.credentials.postgres[:username] %>
  password: <%= Rails.application.credentials.postgres[:password] %>
  host: <%= Rails.application.credentials.postgres[:host] %>
  <% end %>

development:
  primary:
    <<: *default
    database: api_passforge_development
  cache:
    <<: *default
    database: api_passforge_development
    migrations_paths: db/cache_migrate

test:
  primary:
    <<: *default
    database: api_passforge_test
  cache:
    <<: *default
    database: api_passforge_test
    migrations_paths: db/cache_migrate

production:
  primary:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>
  cache:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    url: <%= ENV['DATABASE_URL'] %>
    migrations_paths: db/cache_migrate